name: Build and Push Backend1 Image
on:
  push:
    branches: [dev]
    paths:
      - 'code/backend1/**'
      - 'code/backend2/**'
  pull_request:
    branches: [dev]
    paths:
      - 'code/backend1/**'
      - 'code/backend2/**'


env:
  REGISTRY: docker.io
  BACKEND1_IMAGE_NAME: asmita071/backend1

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' &&(github.head_ref == 'feature' || startsWith(github.head_ref, 'feature/*')) && github.base_ref == 'dev'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Add commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Run Commitlint
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s" | npx commitlint

  lint_backend1:
    runs-on: ubuntu-latest
    needs: commitlint
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature') && github.base_ref == 'dev'
    steps:
      - uses: actions/checkout@v3
      - name: Lint Backend1
        working-directory: ./code/backend1
        run: yarn && yarn lint

  build_push_backend1:
    name: Build & Push Backend1 Image
    runs-on: [self-hosted, backend]
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature') && github.base_ref == 'dev'
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Backend1 Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./code/backend1
          file: ./code/backend1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.BACKEND1_IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && 'prod-latest' || 'dev-latest' }}
