name: Build and Push Frontend Image

on:
  push:
    branches: [dev]
    paths:
      - 'code/frontend/**'
  pull_request:
    branches: [dev]
    paths:
      - 'code/frontend/**'

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: asmita071/frontend

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' &&(github.head_ref == 'feature' || startsWith(github.head_ref, 'feature/*')) && github.base_ref == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Add commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Run Commitlint
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s" | npx commitlint
  check_lint_frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature') && github.base_ref == 'dev'
    needs: [commitlint]
    steps:
      - name: Checkout code  
        uses: actions/checkout@v3
      - name: Lint Frontend(install packages)
        working-directory: ./code/frontend
        run: yarn && yarn lint

  build_frontend:
    name: Build & Push Frontend Image
    runs-on: [self-hosted, frontend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log int to DockerHub  
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./code/frontend
          file: ./code/frontend/Dockerfile
          push: true
          tags: |
                ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.ref_name }}
                ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
